INSERT INTO books (title, author, genre, rating, ratings_count, description) VALUES
('Harry Potter and the Philosopher\'s Stone', 'J.K. Rowling', 'Fantasy', 4.8, 12500, 'A young boy discovers he is a wizard and attends a magical school.'),
('The Hobbit', 'J.R.R. Tolkien', 'Fantasy', 4.7, 10500, 'A hobbit embarks on a journey to help dwarves reclaim their home.'),
('1984', 'George Orwell', 'Dystopian', 4.6, 9800, 'A dystopian society where the government watches everything.'),
('The Catcher in the Rye', 'J.D. Salinger', 'Literary Fiction', 4.2, 7600, 'A troubled young man navigates teenage angst in New York.'),
('Pride and Prejudice', 'Jane Austen', 'Romance', 4.5, 9800, 'A story of love and societal expectations in 19th century England.'),
('To Kill a Mockingbird', 'Harper Lee', 'Classic', 4.9, 13400, 'A young girl witnesses racial injustice in a small southern town.'),
('The Great Gatsby', 'F. Scott Fitzgerald', 'Classic', 4.4, 9000, 'A mysterious millionaire hosts extravagant parties in 1920s New York.'),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 4.9, 15800, 'An epic fantasy tale of the battle between good and evil.'),
('Moby Dick', 'Herman Melville', 'Classic', 4.3, 5400, 'A whaling captain obsessively hunts the white whale.'),
('War and Peace', 'Leo Tolstoy', 'Historical Fiction', 4.6, 8500, 'A sweeping tale of Russian society during the Napoleonic wars.'),
('The Odyssey', 'Homer', 'Epic Poetry', 4.7, 9200, 'The epic journey of Odysseus as he returns home from the Trojan War.'),
('Jane Eyre', 'Charlotte Bronte', 'Romance', 4.6, 10200, 'An orphaned girl becomes a governess and falls in love with her employer.'),
('The Brothers Karamazov', 'Fyodor Dostoevsky', 'Philosophical Fiction', 4.8, 6700, 'A philosophical and theological exploration of free will and morality.'),
('Crime and Punishment', 'Fyodor Dostoevsky', 'Psychological Fiction', 4.7, 7400, 'A man struggles with guilt after committing murder.'),
('Brave New World', 'Aldous Huxley', 'Dystopian', 4.5, 9800, 'A futuristic society controlled by technology and conformity.'),
('The Grapes of Wrath', 'John Steinbeck', 'Historical Fiction', 4.4, 6700, 'A family struggles to survive during the Great Depression.'),
('Frankenstein', 'Mary Shelley', 'Science Fiction', 4.3, 8600, 'A scientist creates a sentient creature that turns on him.'),
('Dracula', 'Bram Stoker', 'Gothic Fiction', 4.4, 7200, 'A vampire terrorizes London in the late 19th century.'),
('Wuthering Heights', 'Emily Bronte', 'Romance', 4.5, 8200, 'A passionate and destructive love affair on the Yorkshire moors.'),
('The Picture of Dorian Gray', 'Oscar Wilde', 'Philosophical Fiction', 4.6, 5400, 'A man remains youthful while his portrait ages and reflects his moral corruption.'),
('Fahrenheit 451', 'Ray Bradbury', 'Dystopian', 4.5, 7600, 'In a future where books are banned, a fireman questions his role in society.'),
('The Chronicles of Narnia', 'C.S. Lewis', 'Fantasy', 4.8, 12500, 'Children discover a magical land called Narnia.'),
('The Alchemist', 'Paulo Coelho', 'Adventure', 4.3, 8800, 'A young shepherd goes on a journey to fulfill his personal legend.'),
('Animal Farm', 'George Orwell', 'Satire', 4.6, 9200, 'A farm is overtaken by animals who seek equality, but face tyranny.'),
('The Da Vinci Code', 'Dan Brown', 'Thriller', 4.1, 11000, 'A symbologist uncovers a religious conspiracy while investigating a murder.'),
('The Shining', 'Stephen King', 'Horror', 4.7, 9400, 'A family becomes the caretakers of a haunted hotel in the mountains.'),
('A Tale of Two Cities', 'Charles Dickens', 'Historical Fiction', 4.4, 8600, 'A tale of revolution and redemption set during the French Revolution.'),
('Gone with the Wind', 'Margaret Mitchell', 'Historical Fiction', 4.5, 8800, 'A Southern woman fights to survive during and after the Civil War.'),
('The Handmaid\'s Tale', 'Margaret Atwood', 'Dystopian', 4.5, 10000, 'A woman lives under a totalitarian regime that subjugates women.'),
('Les Misérables', 'Victor Hugo', 'Historical Fiction', 4.7, 8900, 'A tale of love, justice, and redemption set during revolutionary France.'),
('The Scarlet Letter', 'Nathaniel Hawthorne', 'Historical Fiction', 4.3, 7500, 'A woman is shamed for having a child out of wedlock in Puritan New England.'),
('The Hitchhiker\'s Guide to the Galaxy', 'Douglas Adams', 'Science Fiction', 4.8, 9600, 'A man is taken on an absurd adventure through space.'),
('Anna Karenina', 'Leo Tolstoy', 'Romance', 4.6, 9200, 'A tragic tale of love, society, and infidelity in Imperial Russia.'),
('Slaughterhouse-Five', 'Kurt Vonnegut', 'Science Fiction', 4.5, 8700, 'A soldier time travels through moments of his life during World War II.'),
('The Catch-22', 'Joseph Heller', 'Satire', 4.3, 7400, 'A soldier tries to stay alive amidst the absurdities of war.'),
('One Hundred Years of Solitude', 'Gabriel Garcia Marquez', 'Magical Realism', 4.8, 9600, 'A multi-generational story of the Buendía family in a fictional town.'),
('A Clockwork Orange', 'Anthony Burgess', 'Dystopian', 4.2, 8800, 'A violent youth is subjected to an experiment in behavioral conditioning.'),
('Don Quixote', 'Miguel de Cervantes', 'Classic', 4.7, 7700, 'A man embarks on a quest to revive chivalry in Spain.'),
('The Road', 'Cormac McCarthy', 'Post-Apocalyptic', 4.6, 9300, 'A father and son journey through a desolate, post-apocalyptic world.'),
('Lolita', 'Vladimir Nabokov', 'Psychological Fiction', 4.1, 6700, 'A man becomes obsessed with a young girl, leading to a disturbing relationship.'),
('Catch-22', 'Joseph Heller', 'Satire', 4.3, 7000, 'A soldier tries to navigate the absurdities of war and bureaucracy.'),
('The Stranger', 'Albert Camus', 'Philosophical Fiction', 4.4, 7200, 'A man is tried for murder after displaying indifference to societal norms.'),
('Rebecca', 'Daphne du Maurier', 'Gothic Fiction', 4.6, 8100, 'A young bride is haunted by the memory of her husband’s first wife.');
